### ISSUE TITLE
Doesn't start

### ISSUE THREAD

**Issue by cadeon** [vaxr/mumble-dicebot#1]
$ ruby --version
ruby 1.9.3p0 (2011-10-30 revision 33570) [i686-linux]

$ gem list

**\* LOCAL GEMS ***

eventmachine (0.12.10)
eventually (0.1.1)
ffi (1.1.5)
ffi-rzmq (0.9.6)
json_pure (1.7.5)
protobuf (1.3.0)

$ ./mumble-dicebot -h
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- protobuf/message/message (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from /home/caduffy/mumblebots/vaxr-mumble-dicebot-8ecac0c/msg.rb:294:in `<top (required)>'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from ./mumble-dicebot:8:in`<main>'

**Comment by cadeon** [comment]
It has something to do with require 'protobuf/message/service' - I just ran rprotoc against what seemed to be the original and it generated without that require. Perhaps protobuf has been updated?

It seems to work with the newly generated msg.rb.

**Comment by vaxr** [comment]
Thank you!

I've been running the script with ruby_protobuf (0.4.11) instead of protobuf (1.3.0) before. Switching to protobuf (1.3.0) reproduces the error.

I'll look into it.

**Comment by vaxr** [comment]
I have replaced msg.rb with a version generated by protobuf, which seems to work fine with both.
